server:
  port: 8090
  servlet:
    context-path: /ms-belong-customer-details

spring:
  jmx:
    enabled: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:belongdb;mode=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS belong
    username: belong
    password: belong
  flyway:
    enabled: true
    locations: classpath:db/migration
    check-location: false
    validate-on-migrate: false
    baseline-on-migrate: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        default_schema: belong
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true


logging:
  level:
    org:
      flywaydb: debug
